import { Metadata } from "next";

type Props = {}

const session = null;

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function page({ }: Props) {
  // if (!session) throw new AuthRequiredError();

  return (
    <div>page</div>
  )
}